"""Pydantic schemas for News Intelligence alerts."""

from pydantic import BaseModel
from typing import Optional


class NewsAlert(BaseModel):
    """A single market-impact alert generated by the News Intelligence engine."""
    id: str
    severity: str          # "critical", "high", "medium"
    headline: str
    impact_summary: str
    affected_sectors: list[str]
    recommended_action: str
    asset_name: str        # related ticker / asset
    source: str            # publisher name (e.g. "Reuters")
    url: str               # link to original article
    image_url: Optional[str] = None  # article thumbnail
    timestamp: str         # ISO-8601 string


class NewsAlertListResponse(BaseModel):
    """Wrapper for a list of alerts."""
    alerts: list[NewsAlert]
    total: int
